---
name: Dependabot
on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-approve-merge:
    if: github.event.pull_request.user.login == 'dependabot[bot]' && github.repository == 'lmbbox/gha-workflows'
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      PR_URL: ${{github.event.pull_request.html_url}}
    steps:
      - name: Dependabot Metadata
        id: metadata
        uses: dependabot/fetch-metadata@5e5f99653a5b510e8555840e80cbf1514ad4af38
      - name: Auto-approve for Dependabot PRs
        run: gh pr review --approve "${PR_URL}"
      - name: Auto-merge for Dependabot PRs
        run: gh pr merge --auto --squash "${PR_URL}"
