---
name: Dependabot
on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-approve-merge:
    if: github.event.pull_request.user.login == 'dependabot[bot]' && github.repository == 'lmbbox/gha-workflows'
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
      PR_URL: ${{ github.event.pull_request.html_url }}
    steps:
      - name: Dependabot Metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2.4.0 # ratchet:dependabot/fetch-metadata@v2.4.0
      - name: Auto-approve for Dependabot PRs
        run: gh pr review --approve "${PR_URL}"
      - name: Auto-merge for Dependabot PRs
        run: gh pr merge --auto --squash "${PR_URL}"
