---
name: Opentofu

on:
  workflow_call:
    inputs:
      aws-region:
        description: The AWS region to use.
        default: ${{ vars.OPENTOFU_AWS_REGION || vars.AWS_REGION }}
        required: false
        type: string
      aws-role-to-assume:
        description: The AWS role to assume.
        default: ${{ vars.OPENTOFU_AWS_ROLE_TO_ASSUME || vars.AWS_ROLE_TO_ASSUME }}
        required: false
        type: string
      aws-role-to-chain:
        description: The second AWS role to assume.
        default: ${{ vars.OPENTOFU_AWS_ROLE_TO_CHAIN || vars.AWS_ROLE_TO_CHAIN }}
        required: false
        type: string
      aws-role-to-chain-external-id:
        description: The external ID of the second AWS role to assume.
        default: ""
        required: false
        type: string
      pr-comment-always:
        description: If to always post a PR comment with results.
        default: false
        required: false
        type: boolean
      working-directory:
        description: The directory in which to run tofu from.
        required: true
        type: string
    secrets:
      tfvars:
        description: The content to append to the terraform.tfvars file.
        required: false

concurrency:
  group: ${{ inputs.working-directory }}
  cancel-in-progress: false

env:
  TF_PLUGIN_CACHE_DIR: ~/.terraform.d/plugin-cache

jobs:
  opentofu:
    name: Opentofu ${{ inputs.working-directory }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      pull-requests: write
    defaults:
      run:
        shell: bash
        working-directory: ${{ inputs.working-directory }}
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@ec61189d14ec14c8efccab744f656cffd0e33f37 # ratchet:aws-actions/configure-aws-credentials@v6.1.0
        with:
          aws-region: ${{ inputs.aws-region }}
          role-to-assume: ${{ inputs.aws-role-to-assume }}

      - name: Configure Chained AWS Credentials
        if: inputs.aws-role-to-chain != ''
        uses: aws-actions/configure-aws-credentials@ec61189d14ec14c8efccab744f656cffd0e33f37 # ratchet:aws-actions/configure-aws-credentials@v6.1.0
        with:
          aws-region: ${{ inputs.aws-region }}
          role-to-assume: ${{ inputs.aws-role-to-chain }}
          role-external-id: ${{ inputs.aws-role-to-chain-external-id }}
          role-chaining: true
          role-skip-session-tagging: true

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@f2e9fc6c2b355c1890b65e6f6f0e2ac3e6e22f78 # ratchet:aws-actions/amazon-ecr-login@v2.1.2

      - name: Checkout the repository to the runner
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v6.0.2

      - name: Setup Opentofu
        uses: opentofu/setup-opentofu@fc711fa910b93cba0f3fbecaafc9f42fd0c411cb # ratchet:opentofu/setup-opentofu@v2.0.0

      - name: Set additional tfvars
        if: env.TFVARS != ''
        env:
          TFVARS: ${{ secrets.tfvars }}
        run: |
          cat <<EOF >> terraform.tfvars
          # Added by GHA
          ${TFVARS}
          EOF

      - name: Restore Opentofu Plugin Cache
        id: restore-opentofu-plugin-cache
        uses: actions/cache/restore@668228422ae6a00e4ad889ee87cd7109ec5666a7 # ratchet:actions/cache/restore@v5.0.4
        with:
          path: ${{ env.TF_PLUGIN_CACHE_DIR }}
          key: v1-opentofu-plugin-cache-${{ hashFiles(format('{0}/.terraform.lock.hcl', inputs.working-directory)) }}
          restore-keys: |
            v1-opentofu-plugin-cache-${{ runner.os }}-

      - name: Opentofu Init
        id: init
        run: tofu init

      - name: Save Opentofu Plugin Cache
        uses: actions/cache/save@668228422ae6a00e4ad889ee87cd7109ec5666a7 # ratchet:actions/cache/save@v5.0.4
        with:
          path: ${{ env.TF_PLUGIN_CACHE_DIR }}
          key: ${{ steps.restore-opentofu-plugin-cache.outputs.cache-primary-key }}

      - name: Opentofu Format
        id: fmt
        continue-on-error: true
        run: tofu fmt -check -diff

      - name: Opentofu Validate
        id: validate
        continue-on-error: true
        run: tofu validate

      - name: Opentofu Plan
        id: plan
        if: github.event_name == 'pull_request'
        continue-on-error: true
        run: tofu plan -detailed-exitcode -input=false -lock-timeout=15m -out=tfplan

      - name: Opentofu Show
        id: show
        if: github.event_name == 'pull_request'
        continue-on-error: true
        run: tofu show -plan=tfplan 2>&1 | tee "${{ runner.temp }}/tfplan.log"

      - name: Generate PR Comment File
        if: github.event_name == 'pull_request'
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # ratchet:actions/github-script@v9.0.0
        env:
          FMT: "${{ steps.fmt.outputs.stdout }}\n${{ steps.fmt.outputs.stderr }}"
          VALIDATE: "${{ steps.validate.outputs.stdout }}\n${{ steps.validate.outputs.stderr }}"
          PLAN_ERR: "${{ steps.plan.outputs.stderr }}"
        with:
          script: |
            const fs = require('fs');
            const util = require('util');
            const filePath = '${{ runner.temp }}/pr-comment.md';
            const planLog = fs.readFileSync('${{ runner.temp }}/tfplan.log', 'utf8');

            let planDetails = util.stripVTControlCharacters(planLog).trim();
            if (planDetails.length > 63000) {
              planDetails = planDetails.substring(0, 63000) + "...\n\nTruncated! See job for complete details.";
            }

            const fileContent = `### Opentofu ${{ inputs.working-directory }}
            #### Initialization ⚙️\`${{ steps.init.outcome == 'success' && '✅' || '❌' }}\`
            #### Format and Style 📝\`${{ steps.fmt.outcome == 'success' && '✅' || '❌' }}\`

            <details>
            <summary>Show</summary>

            <pre>
            ${util.stripVTControlCharacters(process.env.FMT).trim()}
            </pre>

            </details>

            #### Validation 🤖\`${{ steps.validate.outcome == 'success' && '✅' || '❌' }}\`

            <details>
            <summary>Show</summary>

            <pre>
            ${util.stripVTControlCharacters(process.env.VALIDATE).trim()}
            </pre>

            </details>

            #### Plan 📖\`${{ steps.plan.outputs.exitcode == 2 && '🚧' || (steps.plan.outcome == 'success' && '✅' || '❌') }}\`

            <details>
            <summary>Show</summary>

            <pre>
            ${util.stripVTControlCharacters(process.env.PLAN_ERR).trim()}
            ${planDetails}
            </pre>

            </details>

            *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*
            `;

            fs.writeFileSync(filePath, fileContent);

      - name: Post PR Comment
        id: post-pr-comment
        if: github.event_name == 'pull_request' && inputs.pr-comment-always || (steps.init.outcome != 'success' || steps.fmt.outcome != 'success' || steps.validate.outcome != 'success' || steps.plan.outputs.exitcode != 0)
        uses: marocchino/sticky-pull-request-comment@d4d6b0936434b21bc8345ad45a440c5f7d2c40ff # ratchet:marocchino/sticky-pull-request-comment@v3.0.3
        with:
          header: opentofu-${{ inputs.working-directory }}
          path: ${{ runner.temp }}/pr-comment.md

      - name: Delete Stale PR Comment
        if: github.event_name == 'pull_request' && steps.post-pr-comment.outcome == 'skipped'
        uses: marocchino/sticky-pull-request-comment@d4d6b0936434b21bc8345ad45a440c5f7d2c40ff # ratchet:marocchino/sticky-pull-request-comment@v3.0.3
        with:
          header: opentofu-${{ inputs.working-directory }}
          delete: true

      - name: Opentofu Status
        if: steps.fmt.outcome == 'failure' || steps.validate.outcome == 'failure' || steps.plan.outcome == 'failure'
        run: exit 1

      - name: Opentofu Apply
        if: github.ref_name == github.event.repository.default_branch
        run: tofu apply -auto-approve -input=false -lock-timeout=15m
