---
name: Previews

#on:
#  pull_request:
#    types: [opened, synchronize, reopened, closed]
on:
  workflow_call:
    inputs:
      aws-region:
        description: The AWS region to use.
        required: true
        type: string
      aws-role-to-assume:
        description: The AWS role to assume.
        required: true
        type: string
      bucket:
        description: The S3 Bucket to publish to.
        required: true
        type: string
      directory:
        description: The directory to copy to s3.
        required: true
        type: string
      domain:
        description: The base previews domain.
        required: true
        type: string

permissions:
  id-token: write
  pull-requests: write

jobs:
  deploy:
    if: github.event.action != 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # ratchet:aws-actions/configure-aws-credentials@v4.3.1
        with:
          aws-region: ${{ inputs.aws-region }}
          role-to-assume: ${{ inputs.aws-role-to-assume }}

      - name: Copy to S3 Bucket
        run: aws s3 sync ${{ inputs.directory }} s3://${{ inputs.bucket }}/${{ github.event.repository.name }}-pr-${{ github.event.number }} --delete

      - name: Comment PR with preview URL
        uses: marocchino/sticky-pull-request-comment@773744901bac0e8cbb5a0dc842800d45e9b2b405 # ratchet:marocchino/sticky-pull-request-comment@v2.9.4
        with:
          message: |
            🚀 Preview for PR #${{ github.event.number }} is ready:
            👉 https://${{ github.event.repository.name }}-pr-${{ github.event.number }}.${{ inputs.domain }}

  cleanup:
    if: github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # ratchet:aws-actions/configure-aws-credentials@v4.3.1
        with:
          aws-region: ${{ inputs.aws-region }}
          role-to-assume: ${{ inputs.aws-role-to-assume }}

      - name: Remove from S3 Bucket
        run: aws s3 rm s3://${{ inputs.bucket }}/${{ github.event.repository.name }}-pr-${{ github.event.number }} --recursive

      - name: Comment PR cleanup
        uses: marocchino/sticky-pull-request-comment@773744901bac0e8cbb5a0dc842800d45e9b2b405 # ratchet:marocchino/sticky-pull-request-comment@v2.9.4
        with:
          message: |
            🧹 Preview for PR #${{ github.event.number }} has been removed.
