---
name: Publish Container Image (ECR)

on:
  workflow_call:
    inputs:
      aws-region:
        description: The AWS region to use.
        default: ${{ vars.ECR_AWS_REGION || vars.AWS_REGION }}
        required: false
        type: string
      aws-role-to-assume:
        description: The AWS role to assume.
        default: ${{ vars.ECR_AWS_ROLE_TO_ASSUME || vars.AWS_ROLE_TO_ASSUME }}
        required: false
        type: string
      repository:
        description: The ECR repository to use (e.g. "lmbbox/example").
        required: true
        type: string
      build-args:
        description: The build-args to pass to docker/build-push-action.
        required: false
        type: string
      context:
        description: The context to pass to docker/build-push-action.
        required: true
        type: string
      file:
        description: The file to pass to docker/build-push-action.
        required: true
        type: string
      platforms:
        description: The platforms to pass to docker/build-push-action.
        required: true
        type: string

jobs:
  publish-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@ec61189d14ec14c8efccab744f656cffd0e33f37 # ratchet:aws-actions/configure-aws-credentials@v6.1.0
        with:
          aws-region: ${{ inputs.aws-region }}
          role-to-assume: ${{ inputs.aws-role-to-assume }}

      - name: Login to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@f2e9fc6c2b355c1890b65e6f6f0e2ac3e6e22f78 # ratchet:aws-actions/amazon-ecr-login@v2.1.2

      - name: Install cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@cad07c2e89fa2edd6e2d7bab4c1aa38e53f76003 # ratchet:sigstore/cosign-installer@v4.1.1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # ratchet:docker/setup-buildx-action@v4.0.0

      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v6.0.2

      - name: Extract image metadata
        id: metadata
        uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf # ratchet:docker/metadata-action@v6.0.0
        with:
          images: ${{ steps.ecr-login.outputs.registry }}/${{ inputs.repository }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}

      - name: Build and push container image
        id: build-push
        uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f # ratchet:docker/build-push-action@v7.1.0
        with:
          build-args: ${{ inputs.build-args }}
          context: ${{ inputs.context }}
          file: ${{ inputs.file }}
          platforms: ${{ inputs.platforms }}
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          cache-from: type=gha,scope=buildkit-${{ inputs.repository }}
          cache-to: type=gha,ignore-error=true,mode=max,scope=buildkit-${{ inputs.repository }}

      # Sign the resulting container image digest except on PRs.
      # This will only write to the public Rekor transparency log when the Docker
      # repository is public to avoid leaking data. If you would like to publish
      # transparency data even for private images, pass --force to cosign below.
      # https://github.com/sigstore/cosign
      - name: Sign the published container image
        if: ${{ github.event_name != 'pull_request' }}
        env:
          # https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-an-intermediate-environment-variable
          TAGS: ${{ steps.metadata.outputs.tags }}
          DIGEST: ${{ steps.build-push.outputs.digest }}
        # This step uses the identity token to provision an ephemeral certificate
        # against the sigstore community Fulcio instance.
        run: echo "${TAGS}" | xargs -I {} cosign sign --yes "{}@${DIGEST}"
